# Generated by Django 3.2.7 on 2022-01-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220120_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='MYtitle',
            new_name='title',
        ),
    ]
